const assert = require('node:assert/strict');
const E = require('../dual-track-engine.js');
let assertions=0;
const equal=(actual,expected,label)=>{assert.deepEqual(actual,expected,label);assertions++;};
const base={route:'healthyAligned',rawP:'P2',executionP:'P2',q:'Q3',p3Context:'PB',obstacleState:'none',hardVetoes:[]};
const calc=patch=>E.calculate({...base,...patch});
equal(calc({route:'mixedTransition'}).size,.5,'Mixed P2 Q3 upgrade');
equal(calc({rawP:'P3',positionTreatment:'p2Effective'}).size,.5,'P3-origin Q3 cap');
equal(calc({q:'Q2',q2Codes:['R','S'],structured:true}).size,.25,'High Negative: .5 -> .25');
equal(calc({rawP:'P3',positionTreatment:'p2Effective',q:'Q2'}).size,.5,'Dual Healthy P3-E Q2 upgrade');
equal(calc({rawP:'P3',positionTreatment:'p2Effective',q:'Q2',q2Codes:['S'],structured:true}).size,.25,'Medium blocks Q2 upgrade');
equal(calc({route:'mixedTransition',q2Codes:['S'],structured:true}).size,.25,'Medium blocks Mixed Q3 upgrade');
equal(calc({route:'mixedTransition',q:'Q2',boundary:true}).size,.25,'V1.4-only route');
equal(calc({route:'mixedTransition',q:'Q2',boundary:false}).size,0,'No boundary: no Mixed Q2 route');
equal(calc({route:'mixedTransition',counterMain:true}).size,0,'Counter Main Mixed prohibited');
equal(calc({route:'conflictMain'}).size,.25,'Conflict cap');
equal(calc({hardConflict:true}).size,0,'Hard Conflict');
equal(calc({route:'alignedTransition',rawP:'P1',executionP:'P1'}).size,.25,'Aligned cap');
equal(calc({route:'alignedTransition',q:'Q2'}).size,0,'Aligned Q2 zero');
equal(calc({route:'neutralTransition',rawP:'P1',executionP:'P1',boundary:true}).size,.5,'True boundary');
equal(calc({route:'neutralTransition',rawP:'P1',executionP:'P1',boundary:false}).size,0,'P1 not confirmed boundary');
equal(calc({route:'neutralTransition',q:'Q2'}).size,0,'Neutral P2 Q2 zero');
equal(calc({rawP:'P3',positionTreatment:'p2Effective',p3Context:'EXT'}).objective,'Reaction-first','EXT management');
equal(calc({rawP:'P3',positionTreatment:'p2Effective',p3Context:'MID',structured:true}).runnerEligibility,'No','MID Structured no runner');
for(const patch of [{rawP:'P4'},{executionP:'P4'},{q:'Q1'},{rangeMiddle:true},{controlNegated:true},{hardVetoes:['time violation']},{firstObstacleR:1.49},{obstacleState:'pending'}]) equal(calc(patch).size,0,'No later stage rescues zero');
equal(calc({firstObstacleR:1.5}).size,1,'1.5 boundary is acceptable, size not auto cut');
equal(calc({firstObstacleR:1.99}).runnerEligibility,'No','RR compressed no runner');
equal(calc({route:'weakAligned',q:'Q2',q2Codes:['F','S']}).size,0,'High .25 -> 0');
equal(calc({route:'reverseHealthyMain',activeHtf:true,clearSweepReclaim:true}).size,0,'Counter Healthy ordinary P2 no');
equal(calc({route:'reverseHealthyMain',rawP:'P1',executionP:'P1',activeHtf:true,clearSweepReclaim:true}).size,.25,'Active P1 counter probe');
equal(calc({route:'reverseWeakMain',activeHtf:true,controlTransfer:true,weakCounterEligible:true}).size,.25,'Counter Weak A/B');
const states=[{type:'healthy',bias:'up'},{type:'weak',bias:'up'},{type:'transition',bias:'up'},{type:'transition',bias:null},{type:'transition',bias:'down'},{type:'weak',bias:'down'},{type:'healthy',bias:'down'}];
const mirror=s=>({...s,bias:s.bias==='up'?'down':s.bias==='down'?'up':null});
for(const main of states)for(const secondary of states)for(const direction of ['Long','Short'])for(const rawP of ['P1','P2','P3','P4'])for(const q of ['Q1','Q2','Q3']){
 const input={...base,main,secondary,direction,rawP,executionP:rawP,q,boundary:true};
 const result=E.calculate(input);
 assert([0,.25,.5,1].includes(result.size));assert(result.size<=result.routeCap);
 const mirrored=E.calculate({...input,main:mirror(main),secondary:mirror(secondary),direction:direction==='Long'?'Short':'Long'});
 equal(result.size,mirrored.size,'Direction mirror');
}
const snapshot={production:{size:.25,objective:'Reaction'},candidate:calc({route:'mixedTransition'}),freezeMode:'pre-outcome'};
const gate={shadowTrade:'Yes',reached2R:'Yes',gateRecorded:'Yes',break:true,acceptance:true,hold:true,extend:true};
equal(E.management(snapshot,{...gate,runnerExitR:4}).unitR,2.4,'80%@2 + 20%@4');
equal(E.management(snapshot,{...gate,runnerExitR:0}).unitR,1.6,'80%@2 + 20%@BE');
equal(E.management(snapshot,{...gate,extend:false,runnerExitR:4}).unitR,2,'Responsive 2R full exit');
equal(E.management(snapshot,{...gate,gateRecorded:'No',runnerExitR:4}).unitR,null,'Unrecorded gate never inferred');
equal(E.management(snapshot,{shadowTrade:'Yes',mfeR:5}).unitR,null,'MFE not a realized result');
let r=E.normalizeRecord({finalSize:.25,entryStatus:'Entry',actualR:.5,mfeR:3.9,dualTrackSnapshot:snapshot,v14Outcome:{...gate,runnerExitR:4}});
equal([r.v14SizeOnlyR,r.v14RunnerOnlyR,r.v14FullR,r.v14DeltaR],[1,.6,1.2,.7],'A/B four tracks use weighted R');
equal(r.reachedTP2,'No','Strictly greater than 3.9');
equal(E.normalizeRecord({...r,mfeR:3.91}).reachedTP2,'Yes','3.91 yes');
equal(E.normalizeRecord({finalSize:0,entryStatus:'Skip',mfeR:4.1,profitR:2}).v13ActualR,null,'Skip never production return');
equal(E.normalizeRecord({finalSize:1,mfeR:null}).reachedTP2,'No','Missing MFE no');
equal(E.normalizeRecord({finalSize:.25,validCandidate:'No'}).validCandidate,'Yes','Automated valid');
equal(E.normalizeRecord({...r,finalSize:1}).finalSize,.25,'Frozen Production protected');
const legacy=E.normalizeRecord({finalSize:.5,profitR:1,entryStatus:'Entry'});
equal(legacy.v14CandidateSize,undefined,'No hindsight backfill');
const original=JSON.stringify(snapshot);
E.management(snapshot,gate);E.calculate(base);equal(JSON.stringify(snapshot),original,'Pure functions do not mutate snapshots');
const counterSnap={production:{size:.25,objective:'Reaction'},candidate:calc({route:'reverseWeakMain',activeHtf:true,controlTransfer:true,weakCounterEligible:true}),candidateInputs:{obstacleState:'none'}};
equal(E.management(counterSnap,{...gate,mainTransitionConfirmed:true,runnerExitR:4}).unitR,2.4,'Counter Weak post-entry transition exception');
equal(E.management(counterSnap,{...gate,mainTransitionConfirmed:false,runnerExitR:4}).unitR,null,'Counter Weak no transition: manual baseline required');
console.log(`PASS: ${assertions} rule and ledger assertions (including 1,176 mirrored state/P/Q combinations).`);
